config/routes.rb
Rails.application.routes.draw do
  root      "static_pages#home"
  get       "/help",    to: "static_pages#help"
  get       "/about",   to: "static_pages#about"
  get       "/contact", to: "static_pages#contact"
  get       "/signup",  to: "users#new"
  get       "/login",   to: "sessions#new"
  post      "/login",   to: "sessions#create"
  delete    "/logout",   to: "sessions#destroy"
  resources :users
end
  #↑この:usersはシンボルでもキーでもなくルート名と呼ばれる文字列。
  #resourcesのようなルーティング生成をするメソッドのことをリソースルーティングヘルパーという

#resources :usersを追加することで使えるようになる名前付きルーティング
#GET	  /users	      index	  users_path	          すべてのユーザーを一覧するページ
#GET	  /users/1	    show	  user_path(user)	      特定のユーザーを表示するページ
#GET	  /users/new	  new	    new_user_path       	ユーザーを新規作成するページ（ユーザー登録）
#POST	  /users	      create	users_path	          ユーザーを作成するアクション
#GET	  /users/1/edit	edit	  edit_user_path(user)	id=1のユーザーを編集するページ
#PATCH	/users/1	    update	user_path(user)	      ユーザーを更新するアクション
#DELETE	/users/1	    destroy	user_path(user)     	ユーザーを削除するアクション

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  #attr_accessorメソッドを使って、仮想属性:remember_tokenを作成
  #attr_accessorメソッドはデータベースに保存される通常の属性へのアクセス、上記のような仮想属性の作成とアクセスができる
  before_save { self.email = email.downcase }
  #↑Userモデルの中では右辺のselfを省略出来る(左辺は不可)
  #before_save { self.email = self.email.downcase }
  #before_save { email.downcase!}
  validates :name,  presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A(?!\+)(?!\-)[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
    #Rubyの標準ライブラリSecureRandomにあるurlsafe_base64メソッドを実行。A–Z、a–z、0–9、"-"、"_"のいずれかの文字（26×2+10+1+1=64種類）からなる長さ22のランダムな文字列を返す。
  end

  #永続的セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def session_token
    remember_digest || remember
  end

  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    #※attr_accessorで定義したアクセッサーではなくローカル変数

    return false if remember_digest.nil?
    #returnキーワードを使う事で、記憶ダイジェストがnilの場合には即座にメソッドを終了している。早期脱出というテクニック。

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
    #これはBCrypt::Password.new(remember_digest)というremember_digestを受け取ってできたBcryptオブジェクトと、is_password?メソッドはBcryptで引数のremember_tokenのハッシュ化を行う。
    #Bcryptオブジェクトにすることによってハッシュ化する時のsalt（ランダム値）を取り出して、　remember_tokenのハッシュ化にも適用させれるのでそれによって一致を確認できる。
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

  #バリデーションメソッドに対して複数のバリデーションオプションを設定出来る。
  #presence 存在チェック
  #length: 長さチェック
  #format:フォーマット検証
  #numericality: 数値であること
  #inclusion: 指定された値のいずれかであること
  #format: 正規表現に一致すること
  #uniqueness: 一意であることを検証。デフォルトだと大文字と小文字を区別している
  ##case_sensitive: falseだと、大文字と小文字を区別しなくなる。
  #また、lengthオプションにはmaximum以外にも
  ##is: 値が特定の値であることをバリデーションします。
  ##in: 値が特定の値のリストに含まれていることをバリデーションします。
  ##within: 値が特定の範囲内にあることをバリデーションします。

  #Railsのコールバックメソッドは、モデルのライフサイクルにおける特定のタイミングで実行されるメソッドです。
  #モデルのオブジェクト作成、更新、削除、保存など、さまざまなイベントにフックして、独自の処理を実行することが
  #できます。
  #主なコールバックメソッド
  #- **before_validation:** バリデーションを行う前に実行されます。
  #- **after_validation:** バリデーションを行った後に実行されます。
  #- **before_save:** 保存前に実行されます。
  #- **after_save:** 保存後に実行されます。
  #- **before_create:** 作成前に実行されます。
  #- **after_create:** 作成後に実行されます。
  #- **before_update:** 更新前に実行されます。
  #- **after_update:** 更新後に実行されます。
  #- **before_destroy:** 削除前に実行されます。
  #- **after_destroy:** 削除後に実行されます。

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end
    #↑ApplicationControllerにSessionsHelperをincludeで読み込ませている
    #ログイン機構はあらゆる場面で使うことになるので、全コントローラの親であるApplicationControllerに読み込ませている
    #こうすることでApplicationControllerを継承している全コントローラでSessionsHelperの使用が可能になる。
    #[予備知識]Helperファイル自体は暗黙的にObjectクラスを継承しているだけで特に他のクラスを継承していない

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session  #ログインの直前に必ずこれを書くこと。セッション固定攻撃への対策になる。
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in user
      redirect_to user
      #user_url(user)のプロフィールページへの変換
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
      #redirect_to user_url(@user)と等価
    else
      render 'new', status: :unprocessable_entity
    end
  end
   
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      if user && session[:session_token] == user.session_token
        @current_user = user
      end
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  #永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
 
  #現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil #安全のため
  end
end


#store メソッドを呼び出していなくても、session[:user_id] に値を代入すると、
#その値はデフォルトで一時クッキーとしてブラウザに保存されます。これは、Rails のセッション管理機能によるものです。
#1.セッション管理機能
# Rails は、session オブジェクトというハッシュを使用して、ユーザーセッション情報を管理します。このハッシュには、
# ユーザーID、ログイン状態など、セッションに関する情報が保存されます。
#2. セッション情報の保存
# session オブジェクトに値を代入すると、その値は自動的にブラウザに送信されます。ブラウザは、この値をクッキーとして保存します。
#3. 一時クッキー
# session オブジェクトに保存された情報は、デフォルトで一時クッキーとして保存されます。一時クッキーは、ブラウザを閉じると
# 消去されます。
#4. store メソッド
# store メソッドは、セッション情報を明示的に保存するために使用されます。このメソッドを呼び出すと、session オブジェクトに
# 保存された情報がブラウザに送信されます。
#5. まとめ
# session オブジェクトに値を代入すると、その値は自動的にブラウザに送信され、一時クッキーとして保存されます。
# store メソッドは、セッション情報を明示的に保存するために使用されます。
#6. 補足
#
#session オブジェクトは、session という名前のヘルパーメソッドを通してアクセスできます。
#store メソッドは、オプションを受け取ることができます。詳細はRailsガイドを参照してください。
#永続cookieに保存するにはparmanentメソッドを使う

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    size        = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/hello/index.html.erb
<div class="codespaces">
  <header class="codespaces-header">
    <img class="codespaces-logo"
         src="railstutorial.png"
         alt="Railsチュートリアル" />
    <p>
      Codespaces
      <span class="heart">♥️</span>
      Railsチュートリアル
    </p>
    <p class="small">
      🎓✨<br>
      ロゴ画像が表示されたらセットアップ完了です!
    </p>
  </header>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
      <%# <ul class="nav navbar-nav navbar-right"> %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" id="account" class="dropdown-toggle">
              Account <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path,
                                       data: { "turbo-method": :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
    <%= debug(params) if Rails.env.development? %>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
 <div class="alert alert-danger">
  The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
  <h1>About</h1>
  <p>
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    is a <a href="https://railstutorial.jp#ebook">book</a> and
    <a href="https://railstutorial.jp/screencast">screencast</a>
    to teach web development with
    <a href="https://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample app for the tutorial.
  </p>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>
  <h1>Help</h1>
  <p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="https://railstutorial.jp/help">Rails Tutorial Help page</a>
    To get help on this sample app, see the
    <a href="https://railsturorial.jp/#ebook">
    <em>Ruby on Rails Tutorial</em>book</a>.
  </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2> 
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  <h2> 
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

  <%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                        "https://rubyonrails.org/" %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%# form_withの引数に使えるキー 
:url : フォーム送信先の URL を指定します。省略すると、現在のページの URL になります。
:model : フォームを関連付けるモデルオブジェクトを指定します。モデルオブジェクトを指定すると、フォーム自動生成機能が利用できます。
:html : フォームタグに属性を追加します。
:method : フォーム送信時の HTTP メソッドを指定します。デフォルトは :post です。
:remote : フォームを非同期送信にするかどうかを指定します。true に設定すると、フォーム送信時にページ遷移せずに JavaScript で処理されます。
:data : フォームタグに data 属性を追加します。
:multipart : フォームが multipart エンコードかどうかを指定します。true に設定すると、ファイルアップロードなどの multipart エンコードに対応できます。
:class : フォームタグに class 属性を追加します。
:id : フォームタグに id 属性を追加します。
:style : フォームタグに style 属性を追加します。
:scope : フォームパラメータのスコープを指定します。デフォルトは :session です。
:defaults : フォーム内のすべてのフィールドにデフォルト値を設定します。
:namespace : フォームの名前空間を指定します。
:wrapper : フォームラッパーを指定します。
:for : フォームを関連付けるオブジェクトを指定します。
%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </aside>
</div>